---
filters: {}
rules:
  preset-ja-technical-writing: true
  "@textlint-ja/no-synonyms": true
  "preset-ja-spacing": 
    "ja-space-between-half-and-full-width":
      "space": "always"
    "ja-space-around-code":
      "before": true
      "after": true
  "@proofdict/proofdict":
    dictURL: https://react-native-jp.github.io/proof-dictionary/
